source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'

gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simple_form'


#remove spring && turbolinks for all future apps 
gem 'bootstrap-sass', '~> 3.3.5'
gem 'devise'

group :development, :test do
	gem 'pry-byebug'
	gem 'better_errors'
	gem 'binding_of_caller'
	gem 'pry-rails'
	gem 'byebug'
	gem 'annotate'
end

